// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DomReady(arg1) {
  return window['go']['backend']['App']['DomReady'](arg1);
}

export function Init() {
  return window['go']['backend']['App']['Init']();
}

export function ScreenshotRecognize() {
  return window['go']['backend']['App']['ScreenshotRecognize']();
}

export function Shutdown(arg1) {
  return window['go']['backend']['App']['Shutdown'](arg1);
}
