// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Auth():Promise<void>;

export function DomReady(arg1:context.Context):Promise<void>;

export function Init():Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;
